apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-api-deployment

spec: 
  replicas: 2

  selector:
    matchLabels:
      app: bookstore-api
  
  template:
    metadata:
      labels:                     # Add the labels key here to match the selector above
        app: bookstore-api
    spec:                          # Add the spec key to define the Pod specification
      containers:                  # Correct the containers key spelling
        - name: book-api
          image: jerry4699/bookstore-api
          ports:
            - containerPort: 3000   # Corrected indentation and placement for ports
