# frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: bookstore-client-service
spec:
  type: NodePort       # Expose the service on the host machine
  selector:
    app: bookstore-client
  ports:
  - port: 8081
    targetPort: 80
    nodePort: 30001
