version: '3.8'

services:
  client:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"  
    networks:
      - app-network
  
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
