apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels: 
    env: development
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80

