apiVersion: v1                  # API version of Kubernetes for the Service resource.
kind: Service                    # Specifies that this is a Service resource.
metadata:
  name: nginx-service            # The name of the Service, which will be used to access it within the cluster.
  labels:
    app: nginx                   # Labels assigned to this Service, useful for identifying and organizing resources.

spec:
  type: ClusterIP                # Type of Service, here "ClusterIP" means it's accessible only within the cluster.
  selector:
    app: nginx                   # Selector used to match this Service to the Pods labeled with "app: nginx".

  ports:
    - protocol: TCP              # Protocol to be used for this Service, typically TCP for web servers.
      port: 80                   # Port on which the Service is exposed within the cluster.
      targetPort: 80            # Port on the Pod that the Service will forward traffic to (container's port).
