name: Bookstore CI/CD

# Define when the workflow should run (on push to the main branch).
on:
  push:
    branches:
      - main

# Define jobs for the workflow.
jobs:
  docker-registry-upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the GitHub repository.
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Build Docker image for the client.
      - name: Build Client Docker Image
        working-directory: ./client
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bookstore:client .

      # Step 3: Build Docker image for the server.
      - name: Build Server Docker Image
        working-directory: ./api
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bookstore:api .

      # Step 4: Authenticate with Docker Hub.
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Push both client and server Docker images to Docker Hub.
      - name: Push Docker Images To Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/bookstore:client
          docker push ${{ secrets.DOCKER_USERNAME }}/bookstore:api

  infra-deploy:
    runs-on: ubuntu-latest
    needs: docker-registry-upload

    steps:
      # Step 1: Checkout the code from the GitHub repository.
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Terraform CLI with the specified version.
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}

      # Step 3: Check the formatting of Terraform files (optional, continue on error).
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        working-directory: ./terraform
        continue-on-error: true

      # Step 4: Initialize Terraform to download providers and set up the backend.
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      # Step 5: Run Terraform Plan to see changes that will be applied.
      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Step 6: Apply the Terraform Plan to deploy infrastructure.
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}

  # Optional: Separate job to destroy infrastructure
  infra-destroy:
    runs-on: ubuntu-latest
    needs: infra-deploy
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Destroy
        working-directory: ./terraform
        run: terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}
